# servers/fastapi/models/presentation_structure_model.py
from typing import List, Optional
from pydantic import BaseModel


class SlideLayout(BaseModel):
    """
    Represents one slide's layout — defines how a slide looks visually.
    Used by hybrid layouts (combines general + modern presentation types).
    """
    id: int
    type: str
    style: str
    color_scheme: Optional[str] = None
    visual: Optional[str] = None
    notes: Optional[str] = None


class SlideContent(BaseModel):
    """
    Represents one slide’s textual and visual content generated by the LLM.
    """
    title: str
    bullets: List[str]
    layout_id: Optional[int] = None  # matches SlideLayout.id
    visuals: Optional[List[str]] = None
    chart_type: Optional[str] = None
    summary: Optional[str] = None


class PresentationStructureModel(BaseModel):
    """
    Defines the full presentation structure generated by the AI —
    mapping slide numbers to layouts and content.
    """
    slides: List[SlideContent]

    def to_string(self) -> str:
        """
        Converts structure to a formatted string for debugging or LLM input.
        """
        return "\n\n".join(
            [
                f"Slide {i+1}: {slide.title}\n"
                f"Layout ID: {slide.layout_id}\n"
                f"Bullets: {', '.join(slide.bullets)}\n"
                f"Visuals: {slide.visuals or 'None'}\n"
                f"Chart: {slide.chart_type or 'None'}\n"
                f"Summary: {slide.summary or 'None'}"
                for i, slide in enumerate(self.slides)
            ]
        )
